dataset_path: "/projects/weilab/dataset/barcode/validation"
output_path: "outputs"
anisotropy: [40, 16, 16]


fiber_segmentation:
  num_gpus: 1
  num_cpus: 16
  batch_size: 64

  checkpoint: /home/linok/skel3d/outputs/checkpoints/01-tiled_clahe/checkpoint_100000.pth.tar
  base_yaml: /home/linok/skel3d/configs/01-tiled_clahe.yaml
  bcs_yaml: /home/linok/skel3d/configs/bcs.yaml

  clahe:
    tile_size: 8
    clip_limit: 2.0

  bcs:
    thres1: 0.21290304093127832
    thres2: 0.6229526243971144
    thres3: 0
    thres4: 0
    thres5: 0
    thres_small: 10


cell_segmentation:
  model_type: "vit_b_lm" # base (also t for tiny; l for large), light microscopy
  visualize: true

skeletonize_fibers:
  num_cpus: 16
  manual_z_scale: 0.33
  percentile_fit: [0.1, 0.9]
  num_centerline_points: 1000
  spline_smoothing: null

precomputed:
  jobs: 64
  chunk_size: [16, 64, 64]
  downsample_factors:
    - [1, 2, 2]
    - [2, 2, 2]
    - [2, 2, 2]
  mesh_mip: 0
  mesh_merge_magnitude: 3
